### ISSUE TITLE
Update all Plugins to 1.18.2

### ISSUE THREAD

**Issue by kevinxdev** [gigaclub/Base-Plugin#10]
- [ ] gigaclub/Base-Plugin#11
- [ ] gigaclub/Translation-Plugin#5
- [ ] gigaclub/Builder-System-Plugin#5

**Comment by Feier68** [comment]
Builder system 
Translation-Plugin
base 
auf 1.18.2
